# Generated by Django 4.0 on 2024-11-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='share',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'managed': True},
        ),
    ]
