# Generated by Django 5.1.1 on 2024-11-13 02:11

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.date(1943, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2024, 11, 13))], verbose_name='Date of Birth'),
        ),
    ]
