# Generated by Django 5.1.1 on 2024-11-13 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
