# Generated by Django 4.0 on 2024-11-28 06:15

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0009_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.date(1943, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2024, 11, 28))], verbose_name='Date of Birth'),
        ),
    ]
