# Generated by Django 5.1.1 on 2024-11-13 07:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sub_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
