version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${PASS}
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASS}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - backend_network
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "${USER}",
          "--password=${PASS}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis_container
    networks:
      - backend_network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_container
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASS}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - mysql
      - redis
    networks:
      - backend_network
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: django-db
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASS}
      REDIS_HOST: redis
    depends_on:
      - redis
      - mysql
    networks:
      - backend_network
    command: celery -A your_project worker --loglevel=info

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: django-db
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASS}
      REDIS_HOST: redis
    depends_on:
      - redis
      - mysql
    networks:
      - backend_network
    command: celery -A your_project beat --loglevel=info

networks:
  backend_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
