version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - backend_network
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: redis_container
    networks:
      - backend_network
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: api_container
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    networks:
      - backend_network
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

networks:
  backend_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
